### ISSUE TITLE
Verify why double unwrapping and pointers are used

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#273]
https://github.com/farcaller/zinc/commit/8900158be89ecc10059effca1583d30b5d968e84 introduces some strange syntax.

**Comment by mcoffin** [comment]
* Usage of pointers was fixed as a side-effect of 2f15d444
* I've gone through and grok'd the double-unwrapping. It's because we have a `Vec` full of `Option<Some>`, so when you call `vec.get()`, you get `&Option<Option<Some>>` We unwrap only the first option, asserting that `maybe_pin_index` will be within the bounds of the `Vec`.

Since we're already panicking on the failure of the index dereference, we might as well just use the `Index` trait directly. I'll submit a PR that will make it a little more clear.
