### ISSUE TITLE
Set up test code coverage reports

### ISSUE THREAD

**Issue by farcaller** [hackndev/zinc#69]
It seems that rust binaries can provide coverage data via kcov now that `-g` is fixed (https://github.com/mozilla/rust/issues/690). The problem is that kcov doesn't run on either OS X or Linux/arm hosts (the latter is similar to https://github.com/SimonKagstrom/kcov/issues/18), but works perfectly well on Linux/x86_64.

One option is to build coverage data on travis and then upload it to s3. it doesn't deal with historic coverage results though, but will provide overall coverage state for master/HEAD.

**Comment by SimonKagstrom** [comment]
kcov should work better with rust since a few commits back (by Kang Seonghoon), and while I very irregularly test ARM support, there was a few fixes to get it working a few months ago (albeit with very limited testing).

And kcov actually supports coveralls.io as well these days, basically just run it with '''--coveralls-id=$TRAVIS_JOB_ID''' from the travis build script.

**Comment by farcaller** [comment]
Yup, I tested the functionality today and it works just fine for us. Thanks for pointing out coveralls integration, that sounds very useful.

**Comment by farcaller** [comment]
This is now done.
